name: Desplegar Frontend en S3 y CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- NUEVO PASO DE DEPURACIÓN ---
      # Este paso nos mostrará la estructura de carpetas exacta.
      - name: List files in the workspace
        run: ls -R

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./medAndBeauty/frontend s3://distribuidoramedandbeauty.com --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id EU2HA5FB18SYH --paths "/*"
