name: Test GitHub Actions Trigger

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "¡El workflow de prueba se ha ejecutado correctamente!"